### ISSUE TITLE
Tem page name font

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/Heide-Cook#96]
Make 

``` css
.offices .employee h3 { margin-bottom: 0.25rem; font-size: 1.625rem; }
```
